chore: Initial Commit
Moved from ianlewis/todos/actions/issue-reopener/

Signed-off-by: Ian Lewis <ianmlewis@gmail.com>

diff --git a/.github/workflows/pre-submit.units.yml b/.github/workflows/pre-submit.units.yml
--- a/.github/workflows/pre-submit.units.yml
+++ b/.github/workflows/pre-submit.units.yml
@@ -26,6 +26,59 @@ permissions:
   contents: read # Needed to check out the repo.
 
 jobs:
+  # Unit tests for TypeScript code
+  ######################################
+
+  ts-tests:
+    name: TypeScript unit tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
+        with:
+          node-version: 16
+      - name: unit tests
+        run: |
+          make unit-test
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: "coverage/cobertura-coverage.xml"
+          fail_ci_if_error: true
+
+  # check-dist for actions
+  ###############################
+
+  check-dist:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+
+      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
+        with:
+          node-version: 16
+
+      - name: Rebuild the dist/ directory
+        run: make clean package
+
+      - name: Compare the expected and actual dist/ directories
+        id: diff
+        run: |
+          set -euo pipefail
+          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+            echo "Detected uncommitted changes after build.  See status below:"
+            git diff
+            exit 1
+          fi
+
+      # If dist/ was different from expected, upload the expected version as an artifact
+      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
+        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
+        with:
+          name: dist
+          path: dist/
+
   # autogen for license headers
   ###############################
 
@@ -109,3 +162,259 @@ jobs:
 
           # Run yamllint
           make yamllint
+
+  eslint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
+        with:
+          node-version: 16
+      - run: make eslint
+
+  # e2e tests.
+  ###############################
+
+  issue-reopener-basic:
+    runs-on: ubuntu-latest
+    # NOTE: Don't run on release since the binaries haven't been created yet.
+    if: ${{ ! startsWith(github.event.pull_request.title, 'chore(release):') }}
+    outputs:
+      issue-url: ${{ steps.create-issue.outputs.url }}
+    permissions:
+      issues: write
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - id: create-issue
+        env:
+          GH_TOKEN: ${{ github.token }}
+          PR_URL: ${{ github.event.pull_request.html_url }}
+        run: |
+          body=""
+          if [ "${PR_URL}" != "" ]; then
+            body="Test issue for commit $PR ${PR_URL}"
+          else
+            body="Test issue for commit ${GITHUB_SHA}"
+          fi
+          body="${body}
+          - [Workflow run](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT})"
+
+          url=$(gh issue create -R "${GITHUB_REPOSITORY}" --title "issue-reopener-basic pre-submit test issue" --body "${body}")
+          echo "${url}"
+          gh issue close "${url}"
+          mkdir test
+          echo "// TODO(${url}): still open" > test/test.go
+          echo "url=${url}" >> "${GITHUB_OUTPUT}"
+      - uses: ./
+        with:
+          path: "test/"
+      - env:
+          GH_TOKEN: ${{ github.token }}
+          ISSUE_URL: ${{ steps.create-issue.outputs.url }}
+        run: |
+          # Ensure the issue was reopened.
+          state=$(gh issue view "${ISSUE_URL}" --json state | jq -r '.state')
+          [ "${state}" == "OPEN" ]
+
+          # Check that the body contains the right path
+          # NOTE: Need to get text output in order to get issue comments.
+          body=$(gh issue view "${ISSUE_URL}" -c)
+          [[ "${body}" == *"1. [test/test.go:1]"* ]]
+
+  issue-reopener-basic-cleanup:
+    runs-on: ubuntu-latest
+    needs: issue-reopener-basic
+    if: ${{ always() }}
+    permissions:
+      issues: write
+    steps:
+      - env:
+          ISSUE_URL: ${{ needs.issue-reopener-basic.outputs.issue-url }}
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # Close the test issue.
+          gh issue close "${ISSUE_URL}" || true
+
+  issue-reopener-dry-run:
+    runs-on: ubuntu-latest
+    # NOTE: Don't run on release since the binaries haven't been created yet.
+    if: ${{ ! startsWith(github.event.pull_request.title, 'chore(release):') }}
+    outputs:
+      issue-url: ${{ steps.create-issue.outputs.url }}
+    permissions:
+      issues: write
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - id: create-issue
+        env:
+          GH_TOKEN: ${{ github.token }}
+          PR_URL: ${{ github.event.pull_request.html_url }}
+        run: |
+          body=""
+          if [ "${PR_URL}" != "" ]; then
+            body="Test issue for commit $PR ${PR_URL}"
+          else
+            body="Test issue for commit ${GITHUB_SHA}"
+          fi
+          body="${body}
+          - [Workflow run](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT})"
+
+          url=$(gh issue create --title "issue-reopener-dry-run pre-submit test issue" --body "${body}")
+          echo "${url}"
+          gh issue close "${url}"
+          mkdir test
+          echo "// TODO(${url}): still open" > test/test.go
+          echo "url=${url}" >> "${GITHUB_OUTPUT}"
+      - uses: ./
+        with:
+          path: "test/"
+          dry-run: true
+      - env:
+          GH_TOKEN: ${{ github.token }}
+          ISSUE_URL: ${{ steps.create-issue.outputs.url }}
+        run: |
+          # Ensure the issue was not reopened.
+          state=$(gh issue view "${ISSUE_URL}" --json state | jq -r '.state')
+          [ "${state}" == "CLOSED" ]
+
+  issue-reopener-dry-run-cleanup:
+    runs-on: ubuntu-latest
+    needs: issue-reopener-dry-run
+    if: ${{ always() }}
+    permissions:
+      issues: write
+    steps:
+      - env:
+          ISSUE_URL: ${{ needs.issue-reopener-dry-run.outputs.issue-url }}
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # Ensure the the test issue is closed even if test fails.
+          gh issue close "${ISSUE_URL}" || true
+
+  issue-reopener-subdir:
+    runs-on: ubuntu-latest
+    # NOTE: Don't run on release since the binaries haven't been created yet.
+    if: ${{ ! startsWith(github.event.pull_request.title, 'chore(release):') }}
+    outputs:
+      issue-url: ${{ steps.create-issue.outputs.url }}
+    permissions:
+      issues: write
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        with:
+          path: "repo"
+
+      - id: create-issue
+        env:
+          GH_TOKEN: ${{ github.token }}
+          PR_URL: ${{ github.event.pull_request.html_url }}
+        run: |
+          body=""
+          if [ "${PR_URL}" != "" ]; then
+            body="Test issue for commit $PR ${PR_URL}"
+          else
+            body="Test issue for commit ${GITHUB_SHA}"
+          fi
+          body="${body}
+          - [Workflow run](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT})"
+
+          url=$(gh issue create -R "${GITHUB_REPOSITORY}" --title "issue-reopener-subdir pre-submit test issue" --body "${body}")
+          echo "${url}"
+          gh issue close "${url}"
+          mkdir -p repo/test
+          echo "// TODO(${url}): still open" > repo/test/test.go
+          echo "url=${url}" >> "${GITHUB_OUTPUT}"
+      - uses: ./repo/
+        with:
+          path: "repo/test"
+      - env:
+          GH_TOKEN: ${{ github.token }}
+          ISSUE_URL: ${{ steps.create-issue.outputs.url }}
+        run: |
+          # Ensure the issue was reopened.
+          state=$(gh issue view "${ISSUE_URL}" --json state | jq -r '.state')
+          [ "${state}" == "OPEN" ]
+
+          # Check that the body contains the right path
+          # NOTE: Need to get text output in order to get issue comments.
+          body=$(gh issue view "${ISSUE_URL}" -c)
+          [[ "${body}" == *"1. [test/test.go:1]"* ]]
+
+  issue-reopener-subdir-cleanup:
+    runs-on: ubuntu-latest
+    needs: issue-reopener-subdir
+    if: ${{ always() }}
+    permissions:
+      issues: write
+    steps:
+      - env:
+          ISSUE_URL: ${{ needs.issue-reopener-subdir.outputs.issue-url }}
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # Close the test issue.
+          gh issue close "${ISSUE_URL}" || true
+
+  issue-reopener-vanityURLs:
+    runs-on: ubuntu-latest
+    # NOTE: Don't run on release since the binaries haven't been created yet.
+    if: ${{ ! startsWith(github.event.pull_request.title, 'chore(release):') }}
+    outputs:
+      issue-url: ${{ steps.create-issue.outputs.url }}
+    permissions:
+      issues: write
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - id: create-issue
+        env:
+          GH_TOKEN: ${{ github.token }}
+          PR_URL: ${{ github.event.pull_request.html_url }}
+        run: |
+          body=""
+          if [ "${PR_URL}" != "" ]; then
+            body="Test issue for commit $PR ${PR_URL}"
+          else
+            body="Test issue for commit ${GITHUB_SHA}"
+          fi
+          body="${body}
+          - [Workflow run](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT})"
+
+          url=$(gh issue create -R "${GITHUB_REPOSITORY}" --title "issue-reopener-vanityURLs pre-submit test issue" --body "${body}")
+          issue_no="${url##*/}"
+          gh issue close "${url}"
+          mkdir test
+          vanity_url="https://golang.org/issues/${issue_no}"
+          echo "${vanity_url}"
+          echo "// TODO(${vanity_url}): still open" > test/test.go
+          echo "vanityURLs:" >> test/issue-reopener.yml
+          echo "- \"^\\\\s*(https?://)?golang.org/issues/(?<id>[0-9]+)\\\\s*$\"" >> test/issue-reopener.yml
+          echo "url=${url}" >> "${GITHUB_OUTPUT}"
+      - uses: ./
+        with:
+          path: "test/"
+          config-path: "test/issue-reopener.yml"
+      - env:
+          GH_TOKEN: ${{ github.token }}
+          ISSUE_URL: ${{ steps.create-issue.outputs.url }}
+        run: |
+          # Ensure the issue was reopened.
+          state=$(gh issue view "${ISSUE_URL}" --json state | jq -r '.state')
+          [ "${state}" == "OPEN" ]
+
+          # Check that the body contains the right path
+          # NOTE: Need to get text output in order to get issue comments.
+          body=$(gh issue view "${ISSUE_URL}" -c)
+          [[ "${body}" == *"1. [test/test.go:1]"* ]]
+
+  issue-reopener-vanityURLs-cleanup:
+    runs-on: ubuntu-latest
+    needs: issue-reopener-vanityURLs
+    if: ${{ always() }}
+    permissions:
+      issues: write
+    steps:
+      - env:
+          ISSUE_URL: ${{ needs.issue-reopener-vanityURLs.outputs.issue-url }}
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # Close the test issue.
+          gh issue close "${ISSUE_URL}" || true
